### ISSUE TITLE
Wildcard node matching

### ISSUE THREAD

**Issue by vardius** [vardius/goserver#4]
Consider following routes:
1. `/:name/x`
2. `/:name/y`

And requests:
1. `/test/x`
2. `/test/y`
3. `/test/z`

Should do:
- request 1. should match route 1
- request 2. should match route 2
- request 3. should match no route

What happens:
- request 1. matches route 1
- request 2. matches no route
- request 3. matches no route

### TODO:
- [x] add test for following case
- [x] confirm if problem exist
- [x] fix it if exist

**Comment by vardius** [comment]
Done #5
